namespace: monitoring

helmCharts:
  - name: kube-prometheus-stack
    releaseName: kube-prometheus-stack
    namespace: monitoring
    version: 76.3.0
    includeCRDs: true
    repo: https://prometheus-community.github.io/helm-charts
    valuesInline:
      grafana:
#        adminUser: admin
#        adminPassword: password
        plugins:
          - grafana-opensearch-datasource

resources:
  - data-sources/opensearch.yaml
