{
 "title": "GPU Training",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values({namespace=\"$namespace\"},job_name)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"default\", pod=~\".*$job.*\"}, host_ip)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$job GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ray_node_gpus_utilization{ray_io_cluster=~\"$job.*\",node_instance=~\"$instance.*\"}",
     "legendFormat": "Node:{{ip}} - GPU:{{GpuIndex}}"
    },
    {}
   ]
  },
  {
   "title": "Job logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "source = fluent-bit | where match_phrase('kubernetes.pod_name', '$job')| where NOT match_phrase('kubernetes.labels.ray_io/node-type', 'worker' ) | where NOT match_phrase('kubernetes.labels.ray_io/node-type', 'head' ) | sort - @timestamp ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Node CPU Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "instance:node_cpu_utilisation:rate5m{job=\"node-exporter\", instance=~\"$instance.*\"} * 100 != 0 ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Network",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 6, "y": 29 },
   "targets": [
    {
     "expr": "        sum (rate (node_network_receive_bytes_total{device=~\"eth.*\", instance=~\"$instance.*\"}[5m]) * 60 / 1000000/1000) by (instance)",
     "legendFormat": "{{instance}}-rx GBps"
    },
    {
     "expr": "        sum (rate (node_network_transmit_bytes_total{device=~\"eth.*\", instance=~\"$instance.*\"}[5m]) * 60 / 1000000/1000) by (instance)\n",
     "legendFormat": "{{instance}}-tx GBps"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"node-exporter\", instance=~\"$instance.*\"}\n-\n  node_memory_MemFree_bytes{job=\"node-exporter\", instance=~\"$instance.*\"}\n-\n  node_memory_Buffers_bytes{job=\"node-exporter\", instance=~\"$instance.*\"}\n-\n  node_memory_Cached_bytes{job=\"node-exporter\", instance=~\"$instance.*\"}\n)\n",
     "legendFormat": "{{instance}} memory used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node-exporter\", instance=~\"$instance.*\"}",
     "legendFormat": "{{instance}} memory buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node-exporter\", instance=~\"$instance.*\"}",
     "legendFormat": "{{instance}} memory cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter\", instance=~\"$instance.*\"}",
     "legendFormat": "{{instance}} memory free"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{job=\"node-exporter\", instance=~\"$instance.*\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\"}[$__rate_interval])",
     "legendFormat": "{{instance}} {{device}} read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{job=\"node-exporter\", instance=~\"$instance.*\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\"}[$__rate_interval])",
     "legendFormat": "{{instance}} {{device}} written"
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total{job=\"node-exporter\", instance=~\"$instance.*\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\"}[$__rate_interval])",
     "legendFormat": "{{instance}} {{device}} io time"
    }
   ]
  }
 ]
}